# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool: Default
#  vmImage: 'macos-latest'

steps:
- script: |
      echo $(System.HostType)
      echo $(System.JobName)
      echo $(System.ServerType)
      echo $(Agent.ServicePortPrefix)
#      echo "##vso[task.getvariable variable=Build_BuildId;]"
#- task: CmdLine@2
#  inputs:
#    script: 'pod init'
#- task: CocoaPods@0
#  inputs:
#    forceRepoUpdate: false
#- task: Xcode@5
#  inputs:
#    actions: 'build'
#    scheme: ''
#    sdk: 'iphoneos'
#    configuration: 'Release'
#    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
#    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
