# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

#pool: Default
pool: Azure Pipelines
#  vmImage: 'macos-latest'
#   vmImage: 'ubuntu-latest'

steps:
#- task: NodeTool@0
#  inputs:
#    versionSpec: '6.x' 
#- script: |
#      echo $(System.HostType)
#      echo $(System.JobName)
#- task: SSH@0
#  inputs:
#    sshEndpoint: 'n148_local'
#    runOptions: 'inline'
#    inline: |
#      cd /etc
#      ls
#    readyTimeout: '20000'
#- task: UsePythonVersion@0
#  inputs:
#    versionSpec: '3.x'
#    architecture: x64
#- task: PythonScript@0
#  inputs:
#   scriptSource: inline
#   script: print("Hello", "how are you?")
#      echo $(System.ServerType)
#      echo $(Agent.CloudId)
#      echo "##vso[task.getvariable variable=Build_BuildId;]"
#- task: ShellScript@2
#  inputs:
#    scriptPath: 'test.sh'
#- task: PowerShell@2
#  inputs:
#    filePath: 'test.ps1'
#- task: CmdLine@2
#  inputs:
#    script: mkdir test
#- task: CopyFiles@2
#   inputs:
#    Contents: '**'
#    TargetFolder: 'test'
#- task: CocoaPods@0
#  inputs:
#    forceRepoUpdate: false
#- task: Xcode@5
#  inputs:
#    actions: 'build'
#    scheme: ''
#    sdk: 'iphoneos'
#    configuration: 'Release'
#    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
#    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
